// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit.
// Maps public image paths to their intrinsic {width, height} for the <Img> wrapper.
export const IMG_META: Record<string, { width: number; height: number }> = {
  "/images/IMG_0168_62568687.webp": {
    "width": 1242,
    "height": 926
  },
  "/images/IMG_0406_329edae3.webp": {
    "width": 942,
    "height": 2048
  },
  "/images/IMG_04072_616a53b6.webp": {
    "width": 942,
    "height": 2048
  },
  "/images/IMG_04082_1cbffeb5.webp": {
    "width": 942,
    "height": 2048
  },
  "/images/IMG_04092_9765baa8.webp": {
    "width": 942,
    "height": 2048
  },
  "/images/IMG_0410_348baadc.webp": {
    "width": 942,
    "height": 2048
  },
  "/images/IMG_04112_be823761.webp": {
    "width": 942,
    "height": 2048
  },
  "/images/IMG_1805_1ebe3fbe.webp": {
    "width": 1289,
    "height": 801
  },
  "/images/IMG_3626_16186764.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_3628_dafbc59f.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_3630_cb792a6d.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_3689_44830253.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_3691_6ff1d865.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_3902_5f245d4e.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_3906_ba7fc1b4.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_4325_3ec44064.webp": {
    "width": 1290,
    "height": 1676
  },
  "/images/IMG_4326_1d7261a6.webp": {
    "width": 1290,
    "height": 1334
  },
  "/images/IMG_4329_1923ded0.webp": {
    "width": 1290,
    "height": 1638
  },
  "/images/IMG_4332_4a0a19a4.webp": {
    "width": 1290,
    "height": 1121
  },
  "/images/IMG_4333_b4e89027.webp": {
    "width": 1290,
    "height": 1072
  },
  "/images/IMG_4334_9bf1bb29.webp": {
    "width": 1290,
    "height": 1220
  },
  "/images/IMG_4335_472f3fbf.webp": {
    "width": 1290,
    "height": 1391
  },
  "/images/IMG_4337_ba0c5068.webp": {
    "width": 1290,
    "height": 1310
  },
  "/images/IMG_4340_7b6a36cb.webp": {
    "width": 1290,
    "height": 1291
  },
  "/images/IMG_4364_f432348b.webp": {
    "width": 1290,
    "height": 880
  },
  "/images/IMG_4370_0c477870.webp": {
    "width": 1290,
    "height": 1151
  },
  "/images/IMG_4372_6bfce48a.webp": {
    "width": 1290,
    "height": 1059
  },
  "/images/IMG_4576_f7492bb1.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_4579_756badf0.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_4580_44c7ea67.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_4581_badf4fc4.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_4819_6d6b910c.webp": {
    "width": 1920,
    "height": 2560
  },
  "/images/IMG_60272_e57b501a.webp": {
    "width": 1242,
    "height": 1546
  },
  "/images/deck-d_ba634a4b.webp": {
    "width": 768,
    "height": 1024
  },
  "/images/deck-e_8b339fcc.webp": {
    "width": 900,
    "height": 750
  },
  "/images/deck-extra1_a653372e.webp": {
    "width": 830,
    "height": 550
  },
  "/images/deck-extra2_d67d044b.webp": {
    "width": 1080,
    "height": 720
  },
  "/images/deck-extra3_752de4bf.webp": {
    "width": 1920,
    "height": 1440
  },
  "/images/deck-f_18568bfc.webp": {
    "width": 1920,
    "height": 1440
  },
  "/images/logo_ea5cfcf8.webp": {
    "width": 500,
    "height": 500
  },
  "/images/randolph/brand-collage.webp": {
    "width": 700,
    "height": 451
  },
  "/images/randolph/estimate-1.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/estimate-2.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/estimate-3.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/gallery-1.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/gallery-2.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/gallery-3.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/gallery-4.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/gallery-5.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/gallery-6.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/hero-firepit.webp": {
    "width": 1290,
    "height": 1121
  },
  "/images/randolph/home-1.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-2.webp": {
    "width": 512,
    "height": 330
  },
  "/images/randolph/home-3.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-4.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-5.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-6.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-7.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-8.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/home-9.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/logo-randolph.webp": {
    "width": 700,
    "height": 712
  },
  "/images/randolph/services-1.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/services-2.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/services-3.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/services-4.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/services-5.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/services-6.webp": {
    "width": 512,
    "height": 512
  },
  "/images/randolph/services-7.webp": {
    "width": 512,
    "height": 512
  }
};
