// One-time/idempotent image optimizer.
// Walks client/public/images, converts every JPG/PNG/WEBP to a single optimized
// WebP at max 1920w (quality 80), writes the result alongside the original,
// then deletes the original to reclaim space.
//
// Also writes client/src/lib/imageMeta.ts — a map of public path -> {width,height}
// that the <Img> wrapper uses to set explicit dimensions (kills CLS).
import { readdirSync, statSync, unlinkSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const publicImages = join(root, "client", "public", "images");

const MAX_W = 1920;
const QUALITY = 80;
const EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) walk(p, out);
    else if (EXTS.has(extname(name).toLowerCase())) out.push(p);
  }
  return out;
}

const files = walk(publicImages);
console.log(`Found ${files.length} image files. Optimizing → WebP @ max ${MAX_W}w q${QUALITY}…`);

const meta = {};

for (const file of files) {
  const ext = extname(file).toLowerCase();
  const base = basename(file, ext);
  const dir = dirname(file);
  const webpPath = join(dir, `${base}.webp`);

  try {
    const input = sharp(file, { failOn: "none" });
    const m0 = await input.metadata();
    const targetW = Math.min(m0.width || MAX_W, MAX_W);

    const buf = await sharp(file, { failOn: "none" })
      .rotate() // honor EXIF orientation
      .resize({ width: targetW, withoutEnlargement: true })
      .webp({ quality: QUALITY })
      .toBuffer({ resolveWithObject: true });

    writeFileSync(webpPath, buf.data);

    // Delete the original if it wasn't already .webp at the same name
    if (ext !== ".webp") {
      try {
        unlinkSync(file);
      } catch {}
    }

    // Public-relative path for the meta map
    const publicPath =
      "/" +
      webpPath
        .replace(join(root, "client", "public") + "/", "")
        .split("/")
        .join("/");

    meta[publicPath] = { width: buf.info.width, height: buf.info.height };
    console.log(
      `  ${publicPath.padEnd(50)} ${buf.info.width}×${buf.info.height}  ${(buf.data.length / 1024).toFixed(0)}KB`
    );
  } catch (e) {
    console.warn(`  FAILED on ${file}: ${e.message}`);
  }
}

// Write the dimensions manifest
const tsLines = [
  "// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit.",
  "// Maps public image paths to their intrinsic {width, height} for the <Img> wrapper.",
  "export const IMG_META: Record<string, { width: number; height: number }> = " +
    JSON.stringify(meta, null, 2) +
    ";",
  "",
];
const metaPath = join(root, "client", "src", "lib", "imageMeta.ts");
writeFileSync(metaPath, tsLines.join("\n"));
console.log(`\n✓ Wrote ${Object.keys(meta).length} entries to client/src/lib/imageMeta.ts`);
